// Generated by scripts/split-farm-sprites.mjs. Do not edit by hand; rerun the script instead.
// Images: public/assets/farm/<id>.png. source = sheet x y width height. price is the suggested shop price.
export type FarmCategory = 'crop' | 'farm-decor';
export interface FarmSprite { name: string; category: FarmCategory; price: number; width: number; height: number; source: string }

export const FARM_SPRITES: Record<string, FarmSprite> = {
  "crop-pumpkin": { name: "Pumpkin", category: "crop", price: 12, width: 16, height: 16, source: "plants free.png 64 0 16 16" },
  "crop-carrot": { name: "Carrot", category: "crop", price: 5, width: 15, height: 14, source: "plants free.png 65 16 15 14" },
  "crop-potato": { name: "Potato", category: "crop", price: 5, width: 16, height: 14, source: "plants free.png 64 32 16 14" },
  "crop-tomato": { name: "Tomato", category: "crop", price: 8, width: 15, height: 13, source: "plants free.png 65 49 15 13" },
  "crop-pea": { name: "Peas", category: "crop", price: 8, width: 15, height: 26, source: "plants free.png 65 68 15 26" },
  "fence-wood": { name: "Wooden Fence", category: "farm-decor", price: 10, width: 32, height: 16, source: "farm objects free.png 0 48 32 16" },
  "fence-post": { name: "Fence Post", category: "farm-decor", price: 5, width: 8, height: 16, source: "farm objects free.png 16 16 8 16" },
  "tree-birch": { name: "Birch Tree", category: "farm-decor", price: 20, width: 35, height: 60, source: "farm objects free.png 54 0 35 60" },
  "tree-stump": { name: "Tree Stump", category: "farm-decor", price: 8, width: 25, height: 12, source: "farm objects free.png 105 64 25 12" },
  "chest": { name: "Chest", category: "farm-decor", price: 15, width: 14, height: 12, source: "farm objects free.png 17 68 14 12" },
  "chest-open": { name: "Open Chest", category: "farm-decor", price: 15, width: 14, height: 15, source: "farm objects free.png 17 81 14 15" },
  "flowers-white": { name: "White Flowers", category: "farm-decor", price: 6, width: 14, height: 9, source: "farm objects free.png 33 70 14 9" },
  "flowers-red": { name: "Red Tulips", category: "farm-decor", price: 6, width: 13, height: 13, source: "farm objects free.png 50 66 13 13" },
  "rock": { name: "Rock", category: "farm-decor", price: 5, width: 16, height: 16, source: "farm objects free.png 32 80 16 16" },
  "bush-clover": { name: "Clover Bush", category: "farm-decor", price: 6, width: 16, height: 15, source: "farm objects free.png 48 81 16 15" },
  "haystack": { name: "Haystack", category: "farm-decor", price: 15, width: 32, height: 31, source: "farm objects free.png 64 65 32 31" },
};

/** public/assets/farm/farm-background.png: 20x14 tiles of 16px; crops may only go on the tilled patches. */
export const FARM_BACKGROUND = {"src":"/assets/farm/farm-background.png","tileSize":16,"cols":20,"rows":14,"tilled":[{"col":6,"row":5,"cols":8,"rows":4}]} as const;
