// Generated by scripts/crop-wallpapers.mjs. Do not edit by hand; rerun the script instead.
// Images: public/assets/wallpapers/<file>.png, one seamless tile each (pixel art, shown at whole-number scales).
export interface WallpaperTile { file: string; name: string; width: number; height: number }

export const WALLPAPERS: Record<string, WallpaperTile> = {
  "wallpaper-sage-pinstripe": { file: "wallpaper_01", name: "Sage Pinstripe", width: 16, height: 16 },
  "wallpaper-navy-stripes": { file: "wallpaper_02", name: "Navy Stripes", width: 16, height: 16 },
  "wallpaper-butter-stripes": { file: "wallpaper_03", name: "Butter Stripes", width: 16, height: 16 },
  "wallpaper-walnut-panels": { file: "wallpaper_04", name: "Walnut Panels", width: 16, height: 28 },
  "wallpaper-blush-roses": { file: "wallpaper_05", name: "Blush Roses", width: 48, height: 20 },
  "wallpaper-crimson-roses": { file: "wallpaper_06", name: "Crimson Roses", width: 32, height: 26 },
  "wallpaper-orange-grove": { file: "wallpaper_07", name: "Orange Grove", width: 48, height: 28 },
  "wallpaper-bunny-moon": { file: "wallpaper_08", name: "Bunny Moon", width: 16, height: 28 },
  "wallpaper-snowflake-frost": { file: "wallpaper_09", name: "Snowflake Frost", width: 48, height: 28 },
  "wallpaper-starry-night": { file: "wallpaper_10", name: "Starry Night", width: 16, height: 27 },
};

export const wallpaperSrc = (tile: WallpaperTile) => `/assets/wallpapers/${tile.file}.png`;
